### ISSUE TITLE
TypeError: '<=' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by lokeshkumar380** [BennyThadikaran/stock-pattern#103]
**Describe the Issue**
This issue is happening when I select the TRNG patterns to scan and other platterns are working good for me 

PS C:\dev\ML\folder\stock-pattern\stock-pattern\src> py init.py -f .\stocks_symbol.txt
? Select an option [ ** Excludes Trendlines & Triangles & Harmonics ] [TRNG] Triangles (Symetrical, Ascending, Descending)
Scanning `TRNG` patterns on `daily`. Press Ctrl - C to exit
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 98/98 [00:03<00:00, 32.52it/s]
Got 2 patterns for `trng`.

Run `py init.py --plot trng-daily.json` to view results.

Chart Controls
        q: quit
        n: Next
        p: Previous
Uncaught Exception
Traceback (most recent call last):
  File "C:\dev\ML\folder\stock-pattern\stock-pattern\src\init.py", line 662, in <module>
    plotter.plot()
  File "C:\dev\ML\folder\stock-pattern\stock-pattern\src\Plotter.py", line 153, in plot
    self.fig, axs = mpf.plot(df, **self.plot_args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lokeshkumar03\AppData\Local\Programs\Python\Python311\Lib\site-packages\mplfinance\plotting.py", line 659, in plot
    line_collections.append(_construct_aline_collections(config['alines'], dtix))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by BennyThadikaran** [comment]
I will check and get back to you on this tomorrow.

**Comment by BennyThadikaran** [comment]
I am not able to replicate the error on my side.

Can you share the `trng-daily.json`. Its only two stocks, Also share the OHLC file for those stocks. That should help isolate the error.

**Comment by BennyThadikaran** [comment]
I'll resolve this for now. I havent found this issue on my local files. If you still run into trouble, reopen this issue and provide me the JSON output and OHLC file. I will definitely look into it and get it resolved.

**Comment by lokeshkumar380** [comment]
Hi , I was out in new year . So this is the file 
[VINYLINDIA.csv](https://github.com/user-attachments/files/18298588/VINYLINDIA.csv)
where I am getting this error

**Comment by BennyThadikaran** [comment]
Hi Lokesh,

I tried `py init.py -p trng --sym vinylindia` with the file you provided and it works fine. I could not detect any other patterns. (See screenshots below)

Can you run `py init.py -v` to check the version you're running. The latest is v4.0.8

![Screenshot_2025-01-03_21-07-31](https://github.com/user-attachments/assets/6caed2a0-b0ab-4639-992d-8fface8a60b3)

![Figure_1](https://github.com/user-attachments/assets/30a68918-9281-443c-b17f-fca49cc735ec)

**Comment by lokeshkumar380** [comment]
PS C:\dev\ML\folder\stock-pattern\stock-pattern\src> py init.py  -v

        Stock-Pattern | Version 4.0.8
        Copyright (C) 2023 Benny Thadikaran

        Github: https://github.com/BennyThadikaran/stock-pattern

        This program comes with ABSOLUTELY NO WARRANTY.
        This is free software, and you are welcome to redistribute it
        under certain conditions.
        See license: https://www.gnu.org/licenses/gpl-3.0.en.html#license-text

PS C:\dev\ML\folder\stock-pattern\stock-pattern\src> py init.py  -p trng --sym VINYLINDIA
Scanning `TRNG` patterns on `daily`. Press Ctrl - C to exit
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it] 
Got 1 patterns for `trng`.

Run `py init.py --plot trng-daily.json` to view results.

Chart Controls
        q: quit
        n: Next
        p: Previous
Uncaught Exception
Traceback (most recent call last):
  File "C:\dev\ML\folder\stock-pattern\stock-pattern\src\init.py", line 662, in <module>
    plotter.plot()
  File "C:\dev\ML\folder\stock-pattern\stock-pattern\src\Plotter.py", line 155, in plot
    self.fig, axs = mpf.plot(df, **self.plot_args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lokeshkumar03\AppData\Local\Programs\Python\Python311\Lib\site-packages\mplfinance\plotting.py", line 659, in plot
    line_collections.append(_construct_aline_collections(config['alines'], dtix))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lokeshkumar03\AppData\Local\Programs\Python\Python311\Lib\site-packages\mplfinance\_utils.py", line 999, in _construct_aline_collections
    aconfig = _process_kwargs(alines, _valid_lines_kwargs())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lokeshkumar03\AppData\Local\Programs\Python\Python311\Lib\site-packages\mplfinance\_arg_validators.py", line 343, in _process_kwargs
    valid = vkwargs[key]['Validator'](value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lokeshkumar03\AppData\Local\Programs\Python\Python311\Lib\site-packages\mplfinance\_utils.py", line 521, in <lambda>
    or mcolors.is_color_like(value)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lokeshkumar03\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\colors.py", line 227, in is_color_like
    to_rgba(c)
  File "C:\Users\lokeshkumar03\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\colors.py", line 302, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lokeshkumar03\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\colors.py", line 326, in _to_rgba_no_colorcycle
    if alpha is not None and not 0 <= alpha <= 1:
                                 ^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'int' and 'str'

**Comment by BennyThadikaran** [comment]
Its likely a dependency conflict. Either the matplotlib or mplfinance version is not compatible. 

You can run a `pip freeze` and compare the versions with the one listed in requirements.txt.

I recommend you setup a virtual env whenever to create a python app and install its dependencies within that environment.

Below are the steps for Windows 10

**1. Setup venv and upgrade pip within the environment.**
```bash
# dot character at end indicates current working directory
# For Python 3.8 remove --upgrade-deps. Pip must be manually upgraded. py -m pip install -U pip
py -m venv --upgrade-deps .
```

**2. Activate the virtual environment.**
Make sure environment  is activated before installing any dependencies or running Stock-Patterns scripts.
`.\Scripts\Activate.ps1`

**3. Install the dependencies**
`pip install -r requirements.txt`

Finally run the scan.

Let me know if you still have trouble after following the steps.

**Comment by BennyThadikaran** [comment]
Ah! its looks like misconfiguration in your user.json

`alpha=self.config.get("ALPHA", 0.7)`

The alpha default value is 0 .7. It is expecting a float value. You may have set it to a string `"0.7"` in user.json

**Comment by lokeshkumar380** [comment]
I did not have this property in my user.json , After I added this also, it still breaking with same error

**Comment by BennyThadikaran** [comment]
This looks like a dependency conflict with mplfinance or matplotlib.

You can check the version using `pip freeze`

Compare mplfinance and matplotlib version with the requirements.txt

I highly recommend setting up a virtual environment.

<https://python.land/virtual-environments/virtualenv#How_to_create_a_Python_venv>

Once you setup venv, run `pip install -r requirements` to isolate the dependencies.

Let me know if you need help. Also let me know if it resolves the issue.

Regards,
Benny Thadikaran
